// UNIMPLEMENTED: THIS IS A PLACEHOLDER FOR THE RAINBOW DOORS FROM THE ORIGINAL GAME
// WHICH UPON OPENING SEND A WAVE BACKWARDS THAT MOVES CATS 
// BEHIND THE DOORS X POSTION, THAT ARE ON THE SAME FLOOR OFF THE SCREEN ( TO THE LEFT).